dist: bionic
language: cpp
compiler:
  - clang
  - gcc
script:  
  - mkdir build
  - meson build
  - cd build
  - ninja

before_install:
  - sudo apt update
  - sudo apt install libboost-dev python3-pip build-essential python3-setuptools
  - sudo pip3 install ninja
  - sudo pip3 install meson
